### ISSUE TITLE
Suggestion: move all demos to a `gradio-tools` org on Hugging Face

### ISSUE THREAD

**Issue by abidlabs** [freddyaboulton/gradio-tool#3]
Thoughts on having a `gradio-tools` org on Hugging Face to host all of the built-in demos? I think it would be helpful for discoverability and so that we can easily maintain these Spaces (make sure they're not down, etc.)

**Comment by freddyaboulton** [comment]
I’m starting to think against this because

1. It’s nice to credit the original author in the source code
2. Some demos may be hard to duplicate (env variables / resources)
3. Users will be incentivized and maintain their own clones due to rate limits (HF token automatically duplicates the space now). So we’re not so on the hook to maintain the spaces ourselves.
4. We can write CI to send some predictions to these spaces every hour to make sure they’re functioning properly
